version: "3.8"

services:
  db:
    image: supabase/postgres:15.1.1.61
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
