packages:
  - packages/*
  - apps/*

catalog:
  "@tanstack/react-query": 5.51.21
  "@ts-rest/core": 3.49.3
  "@ts-rest/open-api": 3.49.3
  "@ts-rest/react-query": 3.49.3
  "@ts-rest/serverless": 3.49.3
  "@types/react": 18.2.79
  "@types/node": 22.0.2
  prettier: 3.3.3
  eslint: 9.8.0
  typescript: 5.5.2
  zod: 3.23.8
