packages:
  - packages/*
  - apps/*

catalog:
  react: 19.0.0
  react-dom: 19.0.0
  lucide-react: 0.468.0
  '@types/react': 19.0.1
  '@types/react-dom': 19.0.2
  '@types/node': 22.8.0
  prettier: 3.3.3
  eslint: 9.17.0
  typescript: 5.5.2
