packages:
  - packages/*
  - apps/*

catalog:
  "@tanstack/react-query": 5.51.21
  "@ts-rest/core": 3.51.0
  "@ts-rest/open-api": 3.51.0
  "@ts-rest/react-query": 3.51.0
  "@ts-rest/serverless": 3.51.0
  react: 19.0.0
  react-dom: 19.0.0
  lucide-react: 0.468.0
  "@types/react": 19.0.1
  "@types/react-dom": 19.0.2
  "@types/node": 22.8.0
  prettier: 3.3.3
  eslint: 9.8.0
  typescript: 5.5.2
  zod: 3.23.8
  next: 14.2.5

