import type { RuleSet } from "../types";

export const privateSchoolRuleSet: RuleSet = {
  groups: [
    {
      key: "visibility",
      label: "Visibility & Trust",
      weight: 2,
      rules: [
        "isClaimed",
        "isVerified",
        "hasLogo",
        "hasWebsite",
        "hasWebsiteEduDomain",
        "hasEmailEduDomain",
        "hasGoogleProfile",
      ],
      description:
        "Increase your school's credibility and discoverability with a verified profile, branded logo, and official domains.",
    },
    {
      key: "transparency",
      label: "Transparency",
      weight: 2,
      rules: ["hasFees", "hasTeachers", "hasAcademicPrograms"],
      description:
        "Publishing fee structures, staff, and academic programs builds parent trust and reduces inbound questions.",
    },
    {
      key: "communication",
      label: "Communication & Parent Support",
      weight: 1.5,
      rules: ["hasPhone", "hasEmail", "hasWhatsapp", "hasParentPortal"],
      description:
        "Strong communication channels and parent portals improve engagement and reduce confusion.",
    },
    {
      key: "enrollment",
      label: "Enrollment Experience",
      weight: 1.5,
      rules: ["enrollmentMethod"],
      description:
        "A smooth enrollment experience makes it easier to attract and retain families. Add clear instructions and timelines.",
    },
    {
      key: "systems",
      label: "Digital Infrastructure",
      weight: 1,
      rules: [],
      description:
        "Shows your level of digital maturity across operations like student records, billing, and transport.",
    },
  ],

  ruleMetadata: {
    isClaimed: {
      key: "isClaimed",
      label: "Claimed Organization",
      description: "Indicates the school has reached out.",
      reasons: ["To ensure the information is accurate and approved."],
      actions: ["Administration can contact us to claim the school."],
      requirements: ["Name, email, and phone number."],
      effort: "low",
      includedInPlan: [],
    },
    isVerified: {
      key: "isVerified",
      label: "Verified Organization",
      description:
        "Indicates the school is officially recognized by the government.",
      reasons: ["Build trust with parents", "Qualify for grants and programs"],
      actions: ["Upload government-issued registration PDF or image"],
      requirements: ["Valid business registration document"],
      effort: "medium",
      includedInPlan: ["lead-gen"],
    },
    hasLogo: {
      key: "hasLogo",
      label: "Logo Available",
      description: "Shows the school has a logo.",
      reasons: ["Improves brand recognition", "Boosts visual trust online"],
      actions: ["Upload a high-quality school logo"],
      requirements: ["JPEG/PNG format", "Min. 300x300 resolution"],
      effort: "low",
      includedInPlan: ["lead-gen"],
    },
    hasWebsite: {
      key: "hasWebsite",
      label: "Website Available",
      description: "School has a general website.",
      reasons: ["Improves online visibility", "Central hub for information"],
      actions: ["Link your existing website or request one"],
      requirements: ["Live URL"],
      effort: "medium",
      includedInPlan: ["lead-gen"],
    },
    hasWebsiteEduDomain: {
      key: "hasWebsiteEduDomain",
      label: ".edu Website Domain",
      description: "School uses a domain ending in .edu.",
      reasons: ["Signals legitimacy", "Enables advanced email setups"],
      actions: ["Switch or purchase .edu domain"],
      requirements: [".edu.gy domain or equivalent"],
      effort: "high",
      includedInPlan: ["lead-gen"],
    },
    hasEmailEduDomain: {
      key: "hasEmailEduDomain",
      label: ".edu Email Address",
      description: "School uses a domain-matching email.",
      reasons: ["Looks professional", "Prevents spam filtering"],
      actions: ["Set up email with your domain"],
      requirements: ["Working email like info@school.edu.gy"],
      effort: "medium",
      includedInPlan: ["lead-gen"],
    },
    hasGoogleProfile: {
      key: "hasGoogleProfile",
      label: "Google Business Profile",
      description: "School is listed and findable on Google Maps.",
      reasons: ["Boosts map visibility", "Improves credibility"],
      actions: ["Claim or create Google listing"],
      requirements: ["Google My Business account"],
      effort: "medium",
      includedInPlan: ["lead-gen"],
    },
    hasFees: {
      key: "hasFees",
      label: "Fees Listed",
      description: "Tuition or fee information is publicly available.",
      reasons: ["Enables financial planning", "Reduces inquiries"],
      actions: ["Enter or upload current fee structure"],
      requirements: ["Fee amount or tier information"],
      effort: "low",
      priority: "high",
      priorityReason: "Parents really want this.",
      includedInPlan: [],
    },
    hasTeachers: {
      key: "hasTeachers",
      label: "Teachers Listed",
      description: "Teacher info is available to the public.",
      reasons: ["Improves transparency", "Shows capacity and expertise"],
      actions: ["List faculty and subjects taught"],
      requirements: ["Names and positions of teaching staff"],
      effort: "medium",
      includedInPlan: [],
    },
    hasAcademicPrograms: {
      key: "hasAcademicPrograms",
      label: "Academic Programs",
      description:
        "Academic offerings like grade levels or subjects are listed.",
      reasons: ["Informs parents", "Helps curriculum comparison"],
      actions: ["Upload academic structure or subjects"],
      requirements: ["Levels or subjects by age group"],
      effort: "medium",
      includedInPlan: [],
    },
    hasPhone: {
      key: "hasPhone",
      label: "Phone Number",
      description: "School can be reached by phone.",
      reasons: ["Direct communication", "Faster problem resolution"],
      actions: ["Enter a valid phone number"],
      requirements: ["Working local number"],
      effort: "low",
      includedInPlan: [],
    },
    hasEmail: {
      key: "hasEmail",
      label: "Email Contact",
      description: "School can be contacted by email.",
      reasons: ["Important for formal queries", "Documentation"],
      actions: ["Enter a school email"],
      requirements: ["Active email address"],
      effort: "low",
      includedInPlan: ["lead-gen"],
    },
    hasWhatsapp: {
      key: "hasWhatsapp",
      label: "WhatsApp Contact",
      description: "Parents can message the school via WhatsApp.",
      reasons: ["Most-used app for communication"],
      actions: ["Enter a WhatsApp number"],
      requirements: ["Active WhatsApp number"],
      effort: "low",
      includedInPlan: [],
    },
    hasParentPortal: {
      key: "hasParentPortal",
      label: "Parent Portal",
      description: "School uses a digital portal for parent access.",
      reasons: ["Real-time updates", "Parent involvement"],
      actions: ["Add details about the portal used"],
      requirements: ["Platform info or screenshots"],
      effort: "medium",
      includedInPlan: [],
    },
    enrollmentMethod: {
      key: "enrollmentMethod",
      label: "Enrollment Method",
      description: "School has a defined enrollment process.",
      reasons: ["Reduces parent confusion", "Improves conversion"],
      actions: ["Explain how enrollment works"],
      requirements: ["Form link, WhatsApp flow, or manual steps"],
      effort: "medium",
      includedInPlan: [],
    },
  },
};
