export default function UserHomePage() {
  return (
    <div style={{ padding: "20px", maxWidth: "800px", margin: "auto" }}>
      <h1>Privacy Policy</h1>
      <p>This was generated by ChatGPT, I'll take a look at it later</p>
      <p>
        This Privacy Policy describes how your personal information is
        collected, used, and shared when you visit or make a purchase from our
        application.
      </p>

      <h2>1. Personal Information We Collect</h2>
      <p>
        When you visit the app, we automatically collect certain information
        about your device, including information about your web browser, IP
        address, time zone, and some of the cookies installed on your device.
        Additionally, as you browse the app, we collect information about the
        individual web pages or products that you view, what websites or search
        terms referred you to the app, and information about how you interact
        with the app. We refer to this automatically-collected information as
        “Device Information.”
      </p>

      <h3>We collect Device Information using the following technologies:</h3>
      <ul>
        <li>
          <strong>“Cookies”:</strong> Data files placed on your device or
          computer and often include an anonymous unique identifier.
        </li>
        <li>
          <strong>“Log files”:</strong> Track actions occurring on the app, and
          collect data including your IP address, browser type, Internet service
          provider, referring/exit pages, and date/time stamps.
        </li>
        <li>
          <strong>“Web beacons,” “tags,” and “pixels”:</strong> Electronic files
          used to record information about how you browse the app.
        </li>
      </ul>

      <h2>2. How We Use Your Personal Information</h2>
      <p>
        We use the Order Information that we collect generally to fulfill any
        orders placed through the app (including processing your payment
        information, arranging for shipping, and providing you with invoices
        and/or order confirmations). Additionally, we use this Order Information
        to:
      </p>
      <ul>
        <li>Communicate with you;</li>
        <li>Screen our orders for potential risk or fraud; and</li>
        <li>
          When in line with the preferences you have shared with us, provide you
          with information or advertising relating to our products or services.
        </li>
      </ul>

      <h2>3. Sharing Your Personal Information</h2>
      <p>
        We share your Personal Information with third parties to help us use
        your Personal Information, as described above. For example, we use
        Google Analytics to help us understand how our customers use the app.
        You can read more about how Google uses your Personal Information here:
        <a href="https://policies.google.com/privacy">Google Privacy Policy</a>.
      </p>

      <h2>4. Data Retention</h2>
      <p>
        When you place an order through the app, we will maintain your Order
        Information for our records unless and until you ask us to delete this
        information.
      </p>

      <h2>5. Changes</h2>
      <p>
        We may update this privacy policy from time to time in order to reflect,
        for example, changes to our practices or for other operational, legal,
        or regulatory reasons.
      </p>
    </div>
  );
}
